travis:
  secure:
    BINSTAR_TOKEN: 2Z5/422G+7smR18PAzyhcelvBRzbm0qN5QyvjeX3Lq2Rvc74D++/RMs6uvIKPd0o9vo6CVoABxjB7zVfZ9f3PvI9DKO9T/2Jk28Aib3kY8Q4mF1+cLYVYd52LOPGYjYaz/qX3HRwRudjHZ27GUN2kj3ogqjODM+VPFXY+eZjEKzIRfzRWpyk6xuXrnpKj1MCqnCGv9KuUH4mattoR4ogK91T+9bSE7g82BGT9eFfea5MZTGT/aHlKLoR4Gvxr+EG+D8RLpfd90zu9UomfAqqV7e+r60+0BlJRu/xztTS8NbtfFjTmlJKEqQ6ODFtUrwV1AsCEqwzG8Z3JaitdZe0h8tmrziY0/MG+FXhlTSVnT5o4VsfAvUbnobPLhzpZoYYfL/dhOHjj5mg7YL38tc2+nSAk0qV/ilP6BdO4+Vvq4dadSdw1SjWIoZTNgjtStYhQABbayAmYXvKr3FK15uToYJRNtyW95BgcJyGXDd3C3HTFOrsvrBIXerBLT6+Q36BpzVhOulaIxzWzI6X+7vH5r8f732PwIzgCjINgauP76d+nwCxXm9/K4panTpn2tHNBNrNWUq9EJVeMIzxdkx2zDAehr0ceqf2odgVU84AEVNhy8EUA/ANmQzncWdLrpA2KJfr+cIl7ffrhk5kPVDfO4bkNYTzni6jd3ueFT744vA=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
