appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
bot:
  automerge: true
provider:
  win: azure
travis:
  secure:
    BINSTAR_TOKEN: CXtVhM8tN1sb/P5O+lx4dGY9KaWRvS/EnhpWUAH9DIj/lmQEXTHiVhhJECOWo8a9lPOX8KafHs+K4C5LlbnYN47DOZ8Fo1XEOCOKLy1PE74oPyqwfNahJB7vqqmRD59NXwuK4Gi8mtn92h5f1vAZf4QL8d4qKW6ifs4cQmVRd9N1Tc7eYN7V8vAIjUb0CsJmOBP/5K6eWFgQliuUyCLSUiEW1aPevyM5yfnMBCZvTWOxNaJ2LS7u6P3QMClm8S++cQ6u0BJv7ZBE1XL3g7X4RjiLCfJ/BMOnJBbM+fld9Xe2YNLeCU2ewqCmV3QyIFMWv95cpiFaScn2O2zk0gbosd6niP0xExudASbD2TSZjJYqfp71buLLCDywn+mB6BugPekNdMu0m3SNEiynetTPHveSVp9+vn8lqQBj9pGJxfAtv5JcY90LoXcYfm/SxAziTZTTHeNiMPFGS1Tz1gXewz5+UyNg/O+kAMAB641s2/rv9/b6HPZbCYvkdwKhlzIS3sk5GlsZKmFAnOuz0itKl0naYe7EAtAvMo4Lm/6wY8x4vVFhZjH0NzktauJRbow4w8FgV9de46dFa5LItXQjW7l9dLgE84xp6EjW68IgPbS/1N89MwDd48cWzI7E0INhlim4M4a6yUym75gHaUDp+E1SL5vWEl/hEd65GbrIxng=
